# Generated by Django 5.2 on 2025-09-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name': '문의', 'verbose_name_plural': '문의 목록'},
        ),
        migrations.AlterModelOptions(
            name='recruit',
            options={'ordering': ['-created_at'], 'verbose_name': '채용 정보', 'verbose_name_plural': '채용 정보 목록'},
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='serviceType',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='service_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='서비스 유형'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='개인정보 동의'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='interest',
            field=models.CharField(blank=True, max_length=30, verbose_name='관심 분야'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(verbose_name='문의 내용'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='replied',
            field=models.BooleanField(default=False, verbose_name='답변 여부'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='replied_at',
            field=models.DateTimeField(auto_now=True, verbose_name='답변일시'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='reply_text',
            field=models.TextField(blank=True, verbose_name='답변 내용'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, verbose_name='삭제일시'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='직무명'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='채용 링크'),
        ),
    ]
