# Generated by Django 5.2 on 2025-04-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterattachment',
            name='filename',
        ),
    ]
