# Generated by Django 5.2 on 2025-09-02 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_remove_newsletterattachment_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsubscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': '이메일 구독자', 'verbose_name_plural': '이메일 구독자 목록'},
        ),
        migrations.AlterModelOptions(
            name='newsletterattachment',
            options={'verbose_name': '뉴스레터 첨부파일', 'verbose_name_plural': '뉴스레터 첨부파일 목록'},
        ),
        migrations.AlterModelOptions(
            name='newsletterlog',
            options={'ordering': ['-sent_at'], 'verbose_name': '뉴스레터 로그', 'verbose_name_plural': '뉴스레터 로그 목록'},
        ),
        migrations.AlterModelOptions(
            name='newslettertemplate',
            options={'ordering': ['-updated_at'], 'verbose_name': '뉴스레터 템플릿', 'verbose_name_plural': '뉴스레터 템플릿 목록'},
        ),
        migrations.AlterField(
            model_name='emailsubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='emailsubscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='구독일시'),
        ),
        migrations.AlterField(
            model_name='newsletterattachment',
            name='attachments',
            field=models.FileField(upload_to='newsletters/', verbose_name='첨부파일'),
        ),
        migrations.AlterField(
            model_name='newsletterattachment',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='newsletter.newsletterlog', verbose_name='뉴스레터 로그'),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='message',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='발송일시'),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='content',
            field=models.TextField(verbose_name='템플릿 내용'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='title',
            field=models.CharField(max_length=200, verbose_name='템플릿 제목'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
